DATASET:
  NAME: DELVE_GalGal
  PARAMETERS:
    SIZE: 80000
    OUTDIR: delve_galgal_dataset
    SEED: 1738
BACKGROUNDS:
  PATH: sim/backgrounds
  CONFIGURATIONS: ['CONFIGURATION_1', 'CONFIGURATION_2']
  ITERATE: 1
DISTRIBUTIONS:
  USERDIST_2:
    FILENAME: sim/userdist/source_colors_with_zlens.txt
    MODE: sample
COSMOLOGY:
  PARAMETERS:
    H0: 70
    Om0: 0.3
IMAGE:
  PARAMETERS:
    exposure_time:
      DISTRIBUTION:
        NAME: delve_exposure_time
        PARAMETERS: None
    numPix: 45
    pixel_scale: 0.2636
    psf_type: GAUSSIAN
    read_noise: 0
    ccd_gain:
      DISTRIBUTION:
        NAME: des_ccd_gain
        PARAMETERS: None
SURVEY:
  PARAMETERS:
    BANDS: g,r,i,z
    seeing:
      DISTRIBUTION:
        NAME: delve_seeing
        PARAMETERS: None
    magnitude_zero_point:
      DISTRIBUTION:
        NAME: delve_magnitude_zero_point
        PARAMETERS: None
    sky_brightness: 0
    num_exposures: 1
SPECIES:
  GALAXY_1:
    NAME: DARKLENS
    LIGHT_PROFILE_1:
      NAME: SERSIC_ELLIPSE
      PARAMETERS:
        magnitude: 1000
        center_x: 0.0
        center_y: 0.0
        R_sersic: 6.0
        n_sersic: 4.0
        e1: -0.5
        e2: 0.5
    MASS_PROFILE_1:
      NAME: SIE
      PARAMETERS:
        theta_E:
          DISTRIBUTION:
            NAME: lognormal
            PARAMETERS:
              mean: 0.91629
              sigma: 0.405465
        e1:
          DISTRIBUTION:
            NAME: uniform
            PARAMETERS:
              minimum: -0.5
              maximum: 0.5
        e2:
          DISTRIBUTION:
            NAME: uniform
            PARAMETERS:
              minimum: -0.5
              maximum: 0.5
        center_x: 0.0
        center_y: 0.0
    SHEAR_PROFILE_1:
      NAME: SHEAR
      PARAMETERS:
        gamma1:
          DISTRIBUTION:
            NAME: lognormal
            PARAMETERS:
              mean: -3.5065579
              sigma: 0.621698
        gamma2:
          DISTRIBUTION:
            NAME: lognormal
            PARAMETERS:
              mean: -3.5065579
              sigma: 0.621698
  GALAXY_2:
    NAME: SOURCE
    LIGHT_PROFILE_1:
      NAME: SERSIC_ELLIPSE
      PARAMETERS:
        magnitude: 17
        center_x:
          DISTRIBUTION:
            NAME: uniform
            PARAMETERS:
              minimum: -1.25
              maximum: 1.25
        center_y:
          DISTRIBUTION:
            NAME: uniform
            PARAMETERS:
              minimum: -1.25
              maximum: 1.25
        R_sersic:
          DISTRIBUTION:
            NAME: lognormal
            PARAMETERS:
              mean: -0.693147
              sigma: 0.693147
        n_sersic:
          DISTRIBUTION:
            NAME: lognormal
            PARAMETERS:
              mean: 0.22314
              sigma: 0.81093
        e1:
          DISTRIBUTION:
            NAME: uniform
            PARAMETERS:
              minimum: -0.5
              maximum: 0.5
        e2:
          DISTRIBUTION:
            NAME: uniform
            PARAMETERS:
              minimum: -0.5
              maximum: 0.5
    MASS_PROFILE_1:
      NAME: SIE
      PARAMETERS:
        sigma_v:
          DISTRIBUTION:
            NAME: uniform
            PARAMETERS:
              minimum: 200.0
              maximum: 500.0
        e1:
          DISTRIBUTION:
            NAME: uniform
            PARAMETERS:
              minimum: -0.5
              maximum: 0.5
        e2:
          DISTRIBUTION:
            NAME: uniform
            PARAMETERS:
              minimum: -0.5
              maximum: 0.5
        center_x: 0.0
        center_y: 0.0
  GALAXY_3:
    NAME: SIMLENS
    LIGHT_PROFILE_1:
      NAME: SERSIC_ELLIPSE
      PARAMETERS:
        magnitude: 17
        center_x: 0.0
        center_y: 0.0
        R_sersic:
          DISTRIBUTION:
            NAME: normal
            PARAMETERS:
              mean: 6.0
              std: 1.5
        n_sersic:
          DISTRIBUTION:
            NAME: normal
            PARAMETERS:
              mean: 4.0
              std: 0.8
        e1:
          DISTRIBUTION:
            NAME: uniform
            PARAMETERS:
              minimum: -0.5
              maximum: 0.5
        e2:
          DISTRIBUTION:
            NAME: uniform
            PARAMETERS:
              minimum: -0.5
              maximum: 0.5
    MASS_PROFILE_1:
      NAME: SIE
      PARAMETERS:
        sigma_v:
          DISTRIBUTION:
            NAME: uniform
            PARAMETERS:
              minimum: 150.0
              maximum: 450.0
        e1:
          DISTRIBUTION:
            NAME: uniform
            PARAMETERS:
              minimum: -0.5
              maximum: 0.5
        e2:
          DISTRIBUTION:
            NAME: uniform
            PARAMETERS:
              minimum: -0.5
              maximum: 0.5
        center_x: 0.0
        center_y: 0.0
GEOMETRY:
  CONFIGURATION_1:
    NAME: LENSES
    FRACTION: 0.5
    PLANE_1:
      OBJECT_1: DARKLENS
      PARAMETERS:
        REDSHIFT:
          DISTRIBUTION:
            NAME: uniform
            PARAMETERS:
              minimum: 0.45
              maximum: 0.7499
    PLANE_2:
      OBJECT_1: SOURCE
      PARAMETERS:
        REDSHIFT:
          DISTRIBUTION:
            NAME: uniform
            PARAMETERS:
              minimum: 1.0
              maximum: 2.0
  CONFIGURATION_2:
    NAME: NONLENSES
    FRACTION: 0.5
    PLANE_1:
      OBJECT_1: DARKLENS
      PARAMETERS:
        REDSHIFT:
          DISTRIBUTION:
            NAME: uniform
            PARAMETERS:
              minimum: 0.45
              maximum: 0.7499
    PLANE_2:
      OBJECT_1: DARKLENS
      PARAMETERS:
        REDSHIFT:
          DISTRIBUTION:
            NAME: uniform
            PARAMETERS:
              minimum: 1.0
              maximum: 2.0
