DATASET:
  NAME: DELVE_GalGal
  PARAMETERS:
    SIZE: 100000
    OUTDIR: ../../data/delve_source_3
    SEED: 13
  
DISTRIBUTIONS:
  USERDIST_1:
    FILENAME: ../configs/source_colors_with_zlens.txt
    MODE: sample
  USERDIST_2:
    FILENAME: ../configs/user_lens_g.txt
    MODE: interpolate
    STEP: 100
  USERDIST_3:
    FILENAME: ../configs/user_lens_r.txt
    MODE: interpolate
    STEP: 100
  USERDIST_4:
    FILENAME: ../configs/user_lens_z.txt
    MODE: interpolate
    STEP: 100

COSMOLOGY:
  PARAMETERS:
    H0: 70
    Om0: 0.3
    
IMAGE:
  PARAMETERS:
    exposure_time:
      DISTRIBUTION:
        NAME: des_exposure_time
        PARAMETERS: None
    numPix: 45
    pixel_scale: 0.2636
    psf_type: GAUSSIAN
    read_noise: 0
    ccd_gain:
      DISTRIBUTION:
        NAME: des_ccd_gain
        PARAMETERS: None
        
SURVEY:
    PARAMETERS:
        BANDS: g,r,z
        seeing:
            DISTRIBUTION:
                NAME: des_seeing
                PARAMETERS: None
        magnitude_zero_point: 32.0
        sky_brightness: 5000000
        num_exposures:
            DISTRIBUTION:
                NAME: des_num_exposures
                PARAMETERS: None
    
SPECIES:
  GALAXY_1:
    NAME: DARKLENS
    LIGHT_PROFILE_1:
        NAME: SERSIC_ELLIPSE
        PARAMETERS:
            magnitude: 1.0
            center_x: 0.0
            R_sersic:
                DISTRIBUTION:
                        NAME: uniform
                        PARAMETERS:
                            minimum: 1.0
                            maximum: 4.0
            n_sersic:
                DISTRIBUTION:
                        NAME: uniform
                        PARAMETERS:
                            minimum: 0.5
                            maximum: 6.0
            e1: 
                DISTRIBUTION:
                            NAME: uniform
                            PARAMETERS:
                                minimum: -0.4
                                maximum: 0.4
            e2: 
                DISTRIBUTION:
                            NAME: uniform
                            PARAMETERS:
                                minimum: -0.4
                                maximum: 0.4
    MASS_PROFILE_1:
      NAME: SIE
      PARAMETERS:
        theta_E:
          DISTRIBUTION:
            NAME: uniform
            PARAMETERS:
              minimum: 1
              maximum: 4.0
        e1:
          DISTRIBUTION:
            NAME: uniform
            PARAMETERS:
              minimum: -0.2
              maximum: 0.2
        e2:
          DISTRIBUTION:
            NAME: uniform
            PARAMETERS:
              minimum: -0.2
              maximum: 0.2
        center_x: 0.0
        center_y: 0.0
  GALAXY_2:
    NAME: SOURCE
    LIGHT_PROFILE_1:
      NAME: SERSIC_ELLIPSE
      PARAMETERS:
        magnitude: 17.0
        center_x:
          DISTRIBUTION:
            NAME: uniform
            PARAMETERS:
              minimum: -1.0
              maximum: 1.0
        center_y:
          DISTRIBUTION:
            NAME: uniform
            PARAMETERS:
              minimum: -1.0
              maximum: 1.0
        R_sersic:
          DISTRIBUTION:
            NAME: lognormal
            PARAMETERS:
              mean: -0.693147
              sigma: 0.693147
        n_sersic:
          DISTRIBUTION:
            NAME: lognormal
            PARAMETERS:
              mean: 0.22314
              sigma: 0.81093
        e1:
          DISTRIBUTION:
            NAME: uniform
            PARAMETERS:
              minimum: -0.5
              maximum: 0.5
        e2:
          DISTRIBUTION:
            NAME: uniform
            PARAMETERS:
              minimum: -0.5
              maximum: 0.5
    MASS_PROFILE_1:
      NAME: SIE
      PARAMETERS:
        sigma_v:
          DISTRIBUTION:
            NAME: uniform
            PARAMETERS:
              minimum: 200.0
              maximum: 500.0
        e1:
          DISTRIBUTION:
            NAME: uniform
            PARAMETERS:
              minimum: -0.5
              maximum: 0.5
        e2:
          DISTRIBUTION:
            NAME: uniform
            PARAMETERS:
              minimum: -0.5
              maximum: 0.5
        center_x: 0.0
        center_y: 0.0
 
GEOMETRY:
  CONFIGURATION_1:
    NAME: LENSES
    FRACTION: 1.0
    PLANE_1:
      OBJECT_1: DARKLENS
      PARAMETERS:
        REDSHIFT:
          DISTRIBUTION:
            NAME: uniform
            PARAMETERS:
              minimum: 0.45
              maximum: 0.7499
    PLANE_2:
      OBJECT_1: SOURCE
      PARAMETERS:
        REDSHIFT:
          DISTRIBUTION:
            NAME: uniform
            PARAMETERS:
              minimum: 1.0
              maximum: 2.0