DATASET:
    NAME: TargetData # set a name, this value is only used if you request the h5 file format
    PARAMETERS:
        SIZE: 50000 # number of images in the full datase.
        OUTDIR: pax_orig_target
        SEED: 10 

COSMOLOGY:
    PARAMETERS:
        H0: 70
        Om0: 0.3

IMAGE:
    PARAMETERS:
        exposure_time: 90
        numPix: 40
        pixel_scale: 0.263
        psf_type: 'GAUSSIAN'
        read_noise: 7
        ccd_gain: 6.083

SURVEY:
    PARAMETERS:
        BANDS: g
        seeing:
            DISTRIBUTION:
                NAME: des_seeing
                PARAMETERS: None
        magnitude_zero_point:
            DISTRIBUTION:
                NAME: des_magnitude_zero_point
                PARAMETERS: None
        sky_brightness:
            DISTRIBUTION:
                NAME: des_sky_brightness
                PARAMETERS: None
        num_exposures:
            DISTRIBUTION:
                NAME: des_num_exposures
                PARAMETERS: None

SPECIES:
    GALAXY_1:
        NAME: LENS
        LIGHT_PROFILE_1:
            NAME: SERSIC_ELLIPSE
            PARAMETERS:
                magnitude: 
                    DISTRIBUTION:
                        NAME: uniform
                        PARAMETERS:
                            minimum: 22.0
                            maximum: 25.0
                center_x: 0
                center_y: 0
                R_sersic: 1
                n_sersic: 4
                e1: 0 
                e2: 0.5 

        MASS_PROFILE_1:
            NAME: SIE
            PARAMETERS:
                theta_E:
                    DISTRIBUTION:
                        NAME: uniform
                        PARAMETERS:
                            minimum: 0.5
                            maximum: 3.0
                e1: 
                    DISTRIBUTION:
                        NAME: uniform
                        PARAMETERS:
                            minimum: -0.2
                            maximum: 0.2
                e2: 
                    DISTRIBUTION:
                        NAME: uniform
                        PARAMETERS:
                            minimum: -0.2
                            maximum: 0.2
                center_x: 
                    DISTRIBUTION:
                        NAME: uniform
                        PARAMETERS:
                            minimum: -1
                            maximum: 1
                center_y: 
                    DISTRIBUTION:
                        NAME: uniform
                        PARAMETERS:
                            minimum: -1
                            maximum: 1
        SHEAR_PROFILE_1:
            NAME: SHEAR
            PARAMETERS:
                gamma1:
                    DISTRIBUTION:
                        NAME: uniform
                        PARAMETERS:
                            minimum: -0.05
                            maximum: 0.05
                gamma2: 
                    DISTRIBUTION:
                        NAME: uniform
                        PARAMETERS:
                            minimum: -0.05
                            maximum: 0.05
    GALAXY_2:
        NAME: SOURCE
        LIGHT_PROFILE_1:
            NAME: SERSIC_ELLIPSE
            PARAMETERS:
                magnitude: 
                    DISTRIBUTION:
                        NAME: uniform
                        PARAMETERS:
                            minimum: 19
                            maximum: 24
                center_x: 0.0
                center_y: 0.0
                R_sersic: 
                    DISTRIBUTION:
                        NAME: uniform
                        PARAMETERS:
                            minimum: 0.5
                            maximum: 1
                n_sersic: 
                    DISTRIBUTION:
                        NAME: uniform
                        PARAMETERS:
                            minimum: 2
                            maximum: 4
                e1: 
                    DISTRIBUTION:
                        NAME: uniform
                        PARAMETERS:
                            minimum: -0.2
                            maximum: 0.2
                e2: 
                    DISTRIBUTION:
                        NAME: uniform
                        PARAMETERS:
                            minimum: -0.2
                            maximum: 0.2
        MASS_PROFILE_1:
            NAME: SIE
            PARAMETERS:
                theta_E: 2.0
                e1: 0.1
                e2: -0.1
                center_x: 0.0
                center_y: 0.0

GEOMETRY:
    CONFIGURATION_1:
        NAME: LENSES
        FRACTION: 1.0
        PLANE_1:
            OBJECT_1: LENS
            PARAMETERS:
                REDSHIFT: 0.5
        PLANE_2:
            OBJECT_1: SOURCE
            PARAMETERS:
                REDSHIFT: 2.